import streamlit as st
import datetime

def generate_project_summary_md(project):
    steps = "\n".join([f"- {step}" for step in project['action_steps']])
    md = f"""# {project['project_name']}

**Issue tackled:** {project['issue']}

**Impact estimate:** {project['impact_estimate']}

**Progress:** {project['progress']}%

**Action steps:**
{steps}

**Notes:**  
{project.get('notes', 'No notes yet.')}

---
*Generated by EchoForge Lite – forge your impact!*
"""
    return md

def export_all_projects():
    projects = st.session_state.get('my_projects', [])
    if not projects:
        return "# 🌱 Your Impact Portfolio\n\nNo projects forged yet. Head to the **AI Forge Studio** to start!"
    portfolio = "# 🌟 EchoForge Lite – My Impact Portfolio\n\n"
    portfolio += f"*Created on {datetime.date.today().strftime('%B %d, %Y')}*\n\n"
    for i, proj in enumerate(projects, 1):
        portfolio += f"## {i}. {proj['project_name']}\n\n"
        portfolio += f"- **Issue:** {proj['issue']}\n"
        portfolio += f"- **Estimated Impact:** {proj['impact_estimate']}\n"
        portfolio += f"- **Progress:** {proj['progress']}%\n"
        portfolio += "- **Action Steps:**\n"
        for step in proj['action_steps']:
            portfolio += f"  - {step}\n"
        portfolio += f"- **Notes:** {proj.get('notes', '—')}\n\n"
        portfolio += "---\n\n"
    portfolio += "\n*Forged with ❤️ using EchoForge Lite*"
    return portfolio

def seed_session_state():
    if 'my_projects' not in st.session_state:
        st.session_state.my_projects = [
            {
                "id": 0,
                "issue": "School Lunch Waste in Massachusetts",
                "project_name": "Zero Waste Cafeteria",
                "action_steps": ["Audit daily food waste", "Start a composting bin", "Educate students during lunch"],
                "impact_estimate": "Could reduce waste by 40% in one semester",
                "progress": 25,
                "notes": "Met with cafeteria manager – she's supportive!"
            }
        ]
    if 'community_likes' not in st.session_state:
        from data import get_community_projects
        st.session_state.community_likes = {p['id']: p['likes'] for p in get_community_projects()}
    if 'selected_issue' not in st.session_state:
        st.session_state.selected_issue = ""
